### ISSUE TITLE
Not available on GTM

### ISSUE THREAD

**Issue by cedricyateo** [gtm-templates-simo-ahava/cookie-monster#3]
Hi,

Thanks for this tool. Despite it's not available on the library of GTM : 
https://prnt.sc/12kzkgw

Even thought we can see it if not logged on GTM https://prnt.sc/12kzljf

Weird.
Let us know if it become available, thanks

**Comment by sahava** [comment]
You need to be in a Server container to find the template in the gallery through GTM.
